### ISSUE TITLE
Why does the Fetcher implement TYPE_IN in AND[TYPE_EQ]

### ISSUE THREAD

**Issue by johangirod** [Evaneos/berthe#60]
Why does the implementation of TYPE_IN is forces by the Fetcher instead of being left to the FetcherQueryBuilder ? I'd like to implement the TYPE_IN in mongo but I can't :(

https://github.com/Evaneos/berthe/blob/master/src/Berthe/Fetcher.php#L198

**Comment by oliviermadre** [comment]
The Fetcher is way older than the FetcherQueryBuilder.

addFilter() was the first way to add a filter, and grouping was added to ensure an "in" using "(() or ())" syntax. But you couldn't add several values at that time.
So we've added addFilters to fix this, having an array of values.
We then encountered issues when the array was empty, resulting in a bad sql format : "in ()" 
The decided fix has been to check at the input if the array is empty or not, to invalidate the query gracefully.

**Comment by johangirod** [comment]
Mmmh, the empty array check is okay. Bu the transformation of IN to multiple equals seems completely off the hook. You should use addFilter with array value instead of addFilters

AddFilters should only be a shortcut to 
```php
foreach ($values as $value) {
            $this->addFilter($columnName, $typeFilter, $value, $groupName);
}```

**Comment by oliviermadre** [comment]
Probably...

So, what do you expect from me ?

**Comment by johangirod** [comment]
A go or a no. Everything is ready for merge.

**Comment by oliviermadre** [comment]
You know my feeling about this.
I expect no regression, the foreach seems legit but you have to do more
than that to make things work without any regression.

Le jeu. 13 août 2015 à 16:47, Johan <notifications@github.com> a écrit :

> A go or a no. Everything is ready for merge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Evaneos/berthe/issues/60#issuecomment-130713503>.
>

-- 
*#DéjàLaBas 
<http://www.evaneos.com/infos/evenements/jeu-concours/dejalabas/>* : Grand 
concours de l'été pour gagner un voyage en Turquie ! *(infos) 
<http://www.evaneos.com/infos/evenements/jeu-concours/dejalabas/>*
*Road Trip <http://www.evaneos.com/infos/evenements/etd/2015-roadtrip/> *: 
Des agents des 4 coins du monde vous rencontrent partout en France et à 
Bruxelles... *(infos)* 
<http://www.evaneos.com/infos/evenements/etd/2015-roadtrip/>

**Comment by johangirod** [comment]
If you look at the PR, there is no regression (because of this https://github.com/Evaneos/berthe/blob/master/src/Berthe/DAL/FetcherPGSQLQueryBuilder.php#L85)

**Comment by johangirod** [comment]
We can update the major. I agree I need to take care of TYPE_NOT_IN, but before I do that I want to know that I won't do it for nothing.

The Fetcher is broke right now, because it doesn't permit a custom implementation of TYPE_IN inside queryBuilders. It means that I cannot implement it with standard element in Mongo (http://docs.mongodb.org/manual/reference/operator/query/in/).

So this is a PR to assess this.
